name: CI
# Trigger the CI on pull requests and direct pushes to any branch
on:
  push:
  pull_request:
permissions: read-all
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36

    - name: terraform fmt
      run: terraform fmt -check
      working-directory: ./terraform


  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: '1.20'

    - name: Run tests
      run: go test -v ./...

  build-verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version: '1.20'

    - name: Build
      run: make build

    - name: Verify
      run: make verify

  run-integration-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.7'
      - run: pip install -r requirements.txt
        working-directory: ./integration/test_consumer/
      - name: Build the stack
        run: docker-compose -f docker-compose-integration.yml up -d
        working-directory: ./integration
      - name: Run consumer python script
        run: python check_kafka_output.py
        working-directory: ./integration/test_consumer
      - name: Output filtered log (full log in artifacts)
        run: docker-compose -f docker-compose-integration.yml logs feeds | grep -v "Sending package" | grep -v "Processing Package"
        working-directory: ./integration/
        if: ${{ always() }}
      - name: Dump logs for archive
        run: docker-compose -f docker-compose-integration.yml logs feeds > feeds-log.txt
        working-directory: ./integration/
        if: ${{ always() }}
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: package-feeds log
          path: ./integration/feeds-log.txt
        if: ${{ always() }}
